### ISSUE TITLE
Setup a project with Remix and integrate Firebase as the backend.

### ISSUE THREAD

**Issue by fahadahmed** [Coding-Pixels/drillz#6]
# Overview
Fork the project to create a Remix app. Integrate Firebase to work with the Remix app. Store data with Firestore, use Firebase Authentication for user auth etc.

## Tasks
- [ ] Setup a new Remix app
- [ ] Store data in Firestore
- [ ] Use Firebase Auth for user authentication (username/password)
- [ ] Use Firebase Emulators to do local development

## Out of Context
 - Deployment of the app to cloud infrastructure
